import type { Metadata } from "next";
import "../globals.css";
import { Work_Sans } from 'next/font/google';
import Provider from "@/providers/Providers";


const workSans = Work_Sans({
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap',
});



export const metadata: Metadata = {
    title: "Dealer Request | NANYA CNC",
    description: "Generated by create next app",
};


export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${workSans.className} antialiased tracking-tight`}
            >

                <Provider>
                    {children}
                </Provider>

            </body>
        </html>
    );
}

// 0300