import type { Metadata } from "next";
import "../../globals.css";
import { Work_Sans } from "next/font/google";
import Sidebar from "../../../components/sidebar/Sidebar";
import Provider from "@/providers/Providers";
import AdminGuard from "@/providers/AdminGuard";


const workSans = Work_Sans({
    subsets: ["latin"],
    weight: ["400", "700"],
    display: "swap",
});



export const metadata: Metadata = {
    title: "Admin Dashboard",
    description: "Generated by create next app",
};



export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${workSans.className} antialiased tracking-tight`}>

                <Provider>
                    <AdminGuard>
                        <div className="flex h-screen bg-gray-900">
                            <Sidebar />
                            <div className="flex-1 p-6 overflow-auto">
                                {children}
                            </div>
                        </div>
                    </AdminGuard>
                </Provider>
            </body>
        </html>
    );
}
