import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/home/Header";
import Footer from "@/components/home/Footer";
import UtilityBar from "@/components/home/UtilityBar";
import { Work_Sans } from 'next/font/google';
import Provider from "@/providers/Providers";


const workSans = Work_Sans({
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap',
});



export const metadata: Metadata = {
    title: "NANYA CNC",
    description: "Generated by create next app",
};


export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${workSans.className} antialiased tracking-tight`}
            >

                <Provider>
                    <UtilityBar />
                    <Header />
                    {children}
                </Provider> 

                {/* <script src="//code.tidio.co/q0rbikpfrmby33jbvifhmfwmwzvqgys4.js" async></script> */}

                {/* Footer */}
                <Footer />

            </body>
        </html>
    );
}
